### ISSUE TITLE
Links estão relativos no html

### ISSUE THREAD

**Issue by Diego-Lopes-Ferreira** [Diego-Lopes-Ferreira/Email-sign-generator#9]
### Algumas imagens estão assim:
```html
<td>
     <a href="http://clicknabio.com/solucaut">
            <img style="width: 130px;" src="imgs/icone.png" />
      </a>
</td>
```

Quando o correto seria algo como:
<img style="width: 130px;" src=**"https://solucaut.com.br/imgs/icone.png"** />

**Comment by tashima42** [comment]
Eu arrumei isso na minha branch, tu precisa dar um merge com a "Pedro".
